### ISSUE TITLE
Automatically logs me out when click magic link

### ISSUE THREAD

**Issue by 7alip** [GalloDaSballo/strapi-magic-template#1]
I'm using Strapi v3.2.5. When I click magic link in plugins in order to provide secret key, page is being reloaded and it's logging me out. It always delete `jwtToken` in local storage whenever I click the magic button.

**Comment by GalloDaSballo** [comment]
Can you send me the Strapi Terminal Output?

Are you opening this link on a new tab and logging in without checking the "keep me logged in" box?

**Comment by 7alip** [comment]
I captured the image after screen recording. I'm not opening the link on a new tab. I usually check the "keep me logged in" checkbox.

![image](https://user-images.githubusercontent.com/22167684/98730551-50366f80-2351-11eb-9852-9d01b81ebf4d.png)

This is the latest log in strapi console:

`[2020-11-10T20:35:51.857Z] debug GET /magic/setting (2 ms) 404`

**Comment by GalloDaSballo** [comment]
Very hard to help you with the little info I got.

If you are getting a 401 it means that Strapi is logging you out.
You could test if this is caused by the plugin by temporarily deleting it, then rebuilding the admin panel.

Seeing a 404 in /magic/settings leads me to believe the plugin is not properly working with Strapi.

If you want to use the Strapi-Plugin-Magic you'd probably be better off using this:
https://github.com/GalloDaSballo/strapi-magic-demo

Which uses the compiled version of the package rather than the development version

**Comment by ninjanoir** [comment]
I get the same issue with the 3.4.5 strapi version...
GET /magic/settings (379 ms) 401
impossible to paste the PK in magic panel

**Comment by sizarcorpse** [comment]
> I get the same issue with the 3.4.5 strapi version...
> GET /magic/settings (379 ms) 401
> impossible to paste the PK in magic panel

same thing here.  strapi terminal : "debug GET /magic/settings (1019 ms) 401"
have you figured it out yet?

**Comment by chibi-octi** [comment]
> I get the same issue with the 3.4.5 strapi version...
> GET /magic/settings (379 ms) 401
> impossible to paste the PK in magic panel

Also having the same issue like ninjanoir with 3.4.5 strapi version.

**Comment by GalloDaSballo** [comment]
Can you tell me:
OS
Browser
Node Version
Npm / Yarn Version?

**Comment by chibi-octi** [comment]
> Can you tell me:
> OS
> Browser
> Node Version
> Npm / Yarn Version?

OS: Windows 10
Browser: Microsoft Edge Chromium - Version 88.0.705.53 (Official build) (64-bit)
Node Version: >=10.16.0 <=14.x.x
Npm version: >=6.0.0

I guess I should update the Node and NPM versions?

**Comment by GalloDaSballo** [comment]
Can you try using Chrome?

**Comment by chibi-octi** [comment]
> Can you try using Chrome?

Just tried it on Chrome Version 88.0.4324.104 (Official Build) (64-bit), I got the same result with it logging me out when clicking on the Magic extension.

**Comment by GalloDaSballo** [comment]
If you click any other page do you NOT get logged out?

To tell me Node Version and Npm Version go in a terminal and type:
node -v
npm -v

**Comment by chibi-octi** [comment]
> If you click any other page do you NOT get logged out?
> 
> To tell me Node Version and Npm Version go in a terminal and type:
> node -v
> npm -v

I can click on other plugin such as, Media library, collection types, and general options with no problems. Only when I click on the Magic plugin I get logged out.
 
These are my current versions for Strapi
Node version: v12.19.0 
npm version: 6.14.11

**Comment by GalloDaSballo** [comment]
My assistant had no issues with Windows 10.

I am able to replicate only by using a non super admin.
Are you accessing the Admin Panel with a Super Admin?

**Comment by GalloDaSballo** [comment]
PS: Just updated the code to latest Strapi + using Node 14 (LTS

**Comment by chibi-octi** [comment]
> PS: Just updated the code to latest Strapi + using Node 14 (LTS

I've updated on Windows to version 14.15.4. Also, updated Strapi's node to version 14.15.4 and npm to version 6.14.10. Running Strapi version 3.4.5

I've logged in as a super admin and still get logged out when clicking on the Magic plugin.

Do you think there's an issue with other files within my Strapi backend?

Thanks for the help.

**Comment by GalloDaSballo** [comment]
There may be some different set up in roles.

Check this file: https://github.com/GalloDaSballo/strapi-magic-template/blob/main/plugins/magic/controllers/magic.js

You can see that I'm bouncing you unless you have the role with id 1
It may be (for whatever reason) that your user has a role with a different id.

Try logging out your role, also try removing these checks.

Let me know if this works!

**Comment by GalloDaSballo** [comment]
<img width="645" alt="Screenshot 2021-01-31 at 20 29 51" src="https://user-images.githubusercontent.com/13383782/106395545-12526000-6403-11eb-851d-89fc7539209d.png">
<img width="605" alt="Screenshot 2021-01-31 at 20 29 57" src="https://user-images.githubusercontent.com/13383782/106395549-167e7d80-6403-11eb-82d1-5d099f446443.png">

**Comment by GalloDaSballo** [comment]
I've just pushed an update that:
Changes permission checks to using role name instead of ID
Shows you why you're being bounced from the panel
Also allows you to inject the Magic PK through a .env file using `MAGIC_KEY`

**Comment by chibi-octi** [comment]
> There may be some different set up in roles.
> 
> Check this file: https://github.com/GalloDaSballo/strapi-magic-template/blob/main/plugins/magic/controllers/magic.js
> 
> You can see that I'm bouncing you unless you have the role with id 1
> It may be (for whatever reason) that your user has a role with a different id.
> 
> Try logging out your role, also try removing these checks.
> 
> Let me know if this works!

I was finally able to get the plugin to work by updating the node version to 14.15.4 and npm version to 6.14.10. With Strapi being version 3.4.6. This allowed me to put in my secret key for Magic and have the service work locally on my machine.

However, when I deploy my Strapi backend to Heroku it now fails. The reason seems to be strapi-plugin-magic related. Here's part of the error message

Error: Module not found: Error: Can't resolve '../../components/StrapiStyled' in '/tmp/build_08fa6a3d_/.cache/plugins/strapi-plugin-magic/admin/src/containers/HomePage'

![2021-02-05 09_07_27-hivefolio · Build _ Heroku - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/7189832/107013154-e54ed600-6791-11eb-90ac-fb2c1db855f8.png)

I've been looking on Google for a solution for days on how to fix this issue, but nothing has worked...

Please help me.

**Comment by chibi-octi** [comment]
Thank you so much @GalloDaSballo for resolving the Heruko deploy issue with the release of strapi-plugin-magic version 0.8.3!
